server:
  port: 8080

spring:
  application:
    name: traffic-sign-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  model:
    onnx-path: classpath:model/traffic_sign_model.onnx
    mapping-path: classpath:model/class_mapping.json
