server:
  port: 8080

spring:
  application:
    name: traffic-sign-backend

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3306/traffic_sign_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  model:
    onnx-path: classpath:model/traffic_sign_model.onnx
    mapping-path: classpath:model/class_mapping.json
